{% set name = "apify-fingerprint-datapoints" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apify_fingerprint_datapoints-{{ version }}.tar.gz
  sha256: 785fb5c784956354ef950aae334b30b9c841c6203cd821e8e002bbfeed309355

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - apify_fingerprint_datapoints
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Browser fingerprint datapoints collected by Apify
  license: Apache-2.0
  license_file: LICENSE.md
  home: https://apify.com/
  dev_url: https://github.com/apify/fingerprint-suite
  doc_url: https://docs.apify.com/academy/anti-scraping/techniques/fingerprinting

extra:
  recipe-maintainers:
    - Pijukatel
